## MIT License
##
## Copyright (c) 2020-2021 NVIDIA CORPORATION.
##
## Permission is hereby granted, free of charge, to any person obtaining a
## copy of this software and associated documentation files (the "Software"),
## to deal in the Software without restriction, including without limitation
## the rights to use, copy, modify, merge, publish, distribute, sublicense,
## and/or sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
## DEALINGS IN THE SOFTWARE.##

name: storm_kit
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - cudatoolkit=11.1
  - pytorch
  - torchvision
  - torchaudio
  - pyzmq
  - numpy
  - pytest
  - colorlog
  - pandas
  - tabulate
  - pip
  - sk-video
  - matplotlib
  - quaternion
  - pip:
    - pytorch3d
    - ghalton
    - argcomplete
    - click
    - cloudpickle
    - imageio-ffmpeg
    - pyyaml
    - scipy
    - tqdm
    - urdfpy
    - wheel
    - hydra-core
    - urdf_parser_py
    - sphinx-rtd-theme
    - sphinx
    - sphinx-autodoc-annotation
    - hydra-core
    - urdf_parser_py
    - numpy-quaternion
    - opencv-python
    - open3d
    - m2r2

